/**
 * Landmarks: the named places a student discovers as the fog lifts.
 *
 * Before discovery a landmark only shows a *beacon* — smoke, a light, a
 * silhouette — that reaches over the fog, plus a one-line teaser. Once its
 * anchor tile is charted the name and lore are revealed. The beacon is the
 * hook: students can always see something worth uncovering.
 */

/**
 * beacon   how it shows through the fog (see mapBeacons.js)
 * always   visible from anywhere (tall or bright things); otherwise it shows
 *          once it is a few sections away or inside the glimpse band
 */
const SPECS = {
  lumen: [
    { id: 'lantern-harbor', name: 'Lantern Harbor', entity: 'hall', start: true,
      lore: 'A busy port where every voyage in the Reaches begins. The hall lantern never goes out.' },
    { id: 'fishers-cove', name: 'Fisher’s Cove', find: 'fishers-cove', minor: true, beacon: 'glint',
      teaser: 'Nets are drying on a beach to the west.',
      lore: 'Old Maren mends her nets here and tells anyone who’ll listen about the fish that got away.' },
    { id: 'standing-stones', name: 'The Standing Stones', find: 'standing-stones', minor: true, beacon: 'glint',
      teaser: 'Tall shapes stand in a ring to the west.',
      lore: 'Nine stones in a circle. On the longest day, the sunrise lines up with the gap.' },
    { id: 'scarecrow', name: 'Farmer Tuck’s Scarecrow', find: 'scarecrow', minor: true, beacon: 'glint',
      teaser: 'Someone is standing very still in the fields.',
      lore: 'Tuck gave it a scholar’s hat. The crows now come to it with questions.' },
    { id: 'honey-grove', name: 'Honey Grove', find: 'honey-grove', minor: true, beacon: 'glint',
      teaser: 'A low hum drifts out of the trees.',
      lore: 'Beehives among the blossoms. The honey tastes faintly of cherries.' },
    { id: 'wishing-well', name: 'The Wishing Well', find: 'wishing-well', minor: true, beacon: 'glint',
      teaser: 'Something clinks in the east.',
      lore: 'Drop a coin, make a wish, then go and study. It works better that way.' },
    { id: 'balloon-meadow', name: 'Balloon Meadow', find: 'balloon-meadow', minor: true, beacon: 'glint',
      teaser: 'A striped shape floats above the plains.',
      lore: 'Take the balloon up and you can see halfway across the Reaches.' },
    { id: 'seal-rocks', name: 'Seal Rocks', find: 'seal-rocks', minor: true, beacon: 'glint',
      teaser: 'Barking echoes over the southern water.',
      lore: 'The seals have claimed these rocks. They are not taking visitors.' },
    { id: 'sea-arch', name: 'The Sea Arch', find: 'sea-arch', minor: true, beacon: 'glint',
      teaser: 'Waves crash against something off the south-west coast.',
      lore: 'The sea carved this arch over ten thousand years. Sail through it for luck.' },
    { id: 'escarpment-watch', name: 'Escarpment Watch', find: 'escarpment-watch', minor: true, beacon: 'glint',
      teaser: 'A tower looks down from the cliffs.',
      lore: 'Built to watch for storms. These days it mostly watches sunsets.' },
    { id: 'salt-caravan', name: 'The Salt Caravan', find: 'salt-caravan', minor: true, beacon: 'glint',
      teaser: 'Tents flap at the edge of the dunes.',
      lore: 'Traders cross the Amber Dunes twice a year. They will swap you a story for a question.' },
    { id: 'cloudfoot-springs', name: 'Cloudfoot Springs', find: 'cloudfoot-springs', minor: true, beacon: 'chimney',
      teaser: 'Steam rises from the foothills.',
      lore: 'Hot springs at the foot of the peaks. Perfect after a long exam.' },
    { id: 'amber-obelisk', name: 'The Amber Obelisk', find: 'amber-obelisk', minor: true, beacon: 'glint',
      teaser: 'Something tall glints on a mesa.',
      lore: 'Its carvings are a timeline of everything the dunes have seen.' },
    { id: 'fairy-ring', name: 'The Fairy Ring', find: 'fairy-ring', minor: true, beacon: 'wisps',
      teaser: 'Tiny lights circle deep in the forest.',
      lore: 'Step inside the ring and you will remember one thing you had forgotten.' },
    { id: 'kelp-forest', name: 'Kelp Forest', find: 'kelp-forest', minor: true, beacon: 'glint',
      teaser: 'Dark shapes sway under the western water.',
      lore: 'A forest under the sea. Otters sleep holding hands so they don’t drift apart.' },
    { id: 'trail-cairn', name: 'Trail Cairn', find: 'trail-cairn', minor: true, beacon: 'glint',
      teaser: 'Stacked stones mark a trail into the peaks.',
      lore: 'Every climber adds a stone. Some have been here for centuries.' },
    { id: 'bottle-l2', name: 'Message in a Bottle', find: 'bottle-l2', minor: true, beacon: 'glint',
      teaser: 'Something bobs on the southern swell.',
      lore: '“If you’re reading this, you’re further than I ever got. Keep going.”' },
    { id: 'sleeping-giant', name: 'The Sleeping Giant', find: 'sleeping-giant', minor: true, beacon: 'glint',
      teaser: 'A huge stone face peers out of the forest.',
      lore: 'Moss has grown over his eyebrows. The locals say he is only resting his eyes.' },
    { id: 'goat-ledge', name: 'Goat Ledge', find: 'goat-ledge', minor: true, beacon: 'glint',
      teaser: 'Something is balancing on the mountainside.',
      lore: 'Mountain goats that climb cliffs you would need ropes for.' },
    { id: 'windcutter-pass', name: 'Windcutter Pass', find: 'windcutter-pass', minor: true, beacon: 'glint',
      teaser: 'A trail zigzags into the western peaks.',
      lore: 'The only pass through the Prism Peaks. The wind here carves words into the rock.' },
    { id: 'old-leviathan', name: 'The Old Leviathan', find: 'old-leviathan', minor: true, beacon: 'glint',
      teaser: 'Great white arches rise from the eastern sand.',
      lore: 'The bones of a sea creature from when the dunes were still ocean.' },
    { id: 'frozen-ship', name: 'The Frozen Ship', find: 'frozen-ship', minor: true, beacon: 'glint',
      teaser: 'A mast pokes out of the northern ice.',
      lore: 'Caught by the ice fifty winters ago. Its crew walked home and never looked back.' },
    { id: 'ice-hut', name: 'Ice Fishing Hut', find: 'ice-hut', minor: true, beacon: 'chimney',
      teaser: 'Smoke curls from a tiny hut on the ice.',
      lore: 'The best fish in the north, if you are patient enough.' },
    { id: 'hermit-rock', name: 'Hermit Rock', at: [9, 89], minor: true,
      teaser: 'A lonely island hides far to the west.', lore: 'One tree, one hut, one very happy hermit.' },
    { id: 'gull-isle', name: 'Gull Isle', at: [150, 108], minor: true,
      teaser: 'Gulls wheel over the eastern sea.', lore: 'Every gull in the Reaches seems to have a cousin here.' },
    { id: 'turtle-isle', name: 'Turtle Isle', at: [142, 124], minor: true,
      teaser: 'A small green island in the south-east.', lore: 'Turtles lay their eggs on this beach every spring.' },
    { id: 'driftwood-isle', name: 'Driftwood Isle', at: [12, 138], minor: true,
      teaser: 'Something washed up in the far south-west.', lore: 'Every current in the Reaches ends up here, and so does everything they carry.' },
    { id: 'north-stack', name: 'The North Stack', at: [150, 17], minor: true,
      teaser: 'A dark pillar stands in the northern sea.', lore: 'A tower of rock older than the continent itself.' },
    { id: 'windmill-hill', name: 'Windmill Hill', entity: 'windmill', beacon: 'sails',
      teaser: 'Something turns slowly on a hill to the north.',
      lore: 'Three old windmills grind the vale’s wheat. Locals say they never stop, not even at night.' },
    { id: 'lumen-falls', name: 'Lumen Falls', at: 'falls', beacon: 'mist',
      teaser: 'You can hear rushing water beyond the clouds.',
      lore: 'The river Lumen drops off the escarpment here, throwing rainbows into the spray.' },
    { id: 'mistfen', name: 'Mistfen Lanterns', entity: 'stiltHouse', beacon: 'wisps',
      teaser: 'Little green lights bob above the marsh.',
      lore: 'A stilt house on the edge of Mistfen, lit so the wisps have company.' },
    { id: 'petal-shrine', name: 'Petal Shrine', entity: 'shrine', beacon: 'petals',
      teaser: 'Pink petals drift out of the fog.',
      lore: 'A quiet shrine in Blossomwood where travellers leave a note of something they learned.' },
    { id: 'emberwood-lodge', name: 'Emberwood Lodge', entity: 'lodge', beacon: 'chimney',
      teaser: 'Woodsmoke drifts over the autumn trees.',
      lore: 'A hunters’ lodge among red and gold leaves. The fire is always going.' },
    { id: 'elder-tree', name: 'The Elder Tree', entity: 'elderTree', beacon: 'lanterns', always: true,
      teaser: 'Warm lights hang above the western forest.',
      lore: 'The oldest tree in the Reaches. It holds a lantern for every scholar who rested beneath it.' },
    { id: 'sun-temple', name: 'The Sun Temple', entity: 'temple', beacon: 'beam', always: true,
      teaser: 'A golden beam pierces the sky to the east.',
      lore: 'An ancient pyramid half-buried in the Amber Dunes. At noon its capstone blazes like a second sun.' },
    { id: 'drowned-library', name: 'The Drowned Library', entity: 'library', beacon: 'runes',
      teaser: 'Strange lights shimmer beneath the waves.',
      lore: 'A library that sank long ago. Its shelves still glow: the knowledge never fully drowned.' },
    { id: 'emberforge', name: 'Emberforge', entity: 'volcano', beacon: 'smoke', always: true,
      teaser: 'Smoke rises far out to sea.',
      lore: 'A volcano with a forge at its foot, where smiths shape tools in lava light.' },
    { id: 'prism-caverns', name: 'Prism Caverns', entity: 'crystalCave', beacon: 'prism', always: true,
      teaser: 'Coloured light dances between the peaks.',
      lore: 'Caves full of singing crystals that split a single beam into every colour.' },
    { id: 'skyhaven', name: 'Skyhaven', entity: 'skyhaven', beacon: 'sky', always: true,
      teaser: 'An island… floating in the sky?',
      lore: 'Nobody knows what holds Skyhaven up. Its waterfalls never reach the sea.' },
    { id: 'coral-crown', name: 'Coral Crown', island: 'coral', beacon: 'whale',
      teaser: 'Something huge breathes out in the open sea.',
      lore: 'A ring of coral around a turquoise lagoon. Whales rest in its calm water each summer.' },
    { id: 'frostfang', name: 'Frostfang Glacier', entity: 'igloo', beacon: 'aurora', always: true,
      teaser: 'Curtains of green light ripple in the north.',
      lore: 'Where the ice meets the sea. On clear nights the aurora dances low enough to touch.' },
    { id: 'starfall', name: 'Starfall Observatory', entity: 'observatory', beacon: 'stars', always: true,
      teaser: 'At the top of the world, someone is watching the stars.',
      lore: 'The highest building in the Reaches. Its telescope has mapped every star you can see, and a few you can’t.' },
    { id: 'wanderer-wreck', name: 'Wreck of the Wanderer', entity: 'wreck', beacon: 'glint',
      teaser: 'Something glints on the southern reef.',
      lore: 'The Wanderer ran aground carrying a cargo of maps. A few are still waiting to be found.' },
  ],
  neon: [
    { id: 'port-nova', name: 'Port Nova', entity: 'terminal', start: true,
      lore: 'Where every run through the Meridian begins. The ferries never stop humming.' },
    { id: 'lantern-row', name: 'Lantern Row', region: 'market', beacon: 'lanterns',
      teaser: 'Red lanterns sway between the rooftops.',
      lore: 'A hundred stalls under a thousand signs. The dumplings are legendary.' },
    { id: 'pixel-palace', name: 'The Pixel Palace', entity: 'arcade', beacon: 'arcade',
      teaser: 'Chiptune music drifts out of the smog.',
      lore: 'The oldest arcade in the city. Its high-score table is older than most of the buildings.' },
    { id: 'old-town', name: 'Old Town', entity: 'pagoda', beacon: 'lanterns',
      teaser: 'Old tiled roofs hide between the towers.',
      lore: 'The Meridian was built on top of an older city. Some of its temples still stand.' },
    { id: 'canal-quarter', name: 'The Canal Quarter', region: 'canal', beacon: 'sparkle',
      teaser: 'Neon ripples on water to the west.',
      lore: 'Water taxis drift between glowing bridges. Nobody walks in the Canal Quarter.' },
    { id: 'the-arcology', name: 'The Arcology', entity: 'arcology', beacon: 'crown', always: true,
      teaser: 'A tower so tall its crown glows above the smog.',
      lore: 'Three hundred floors and one elevator queue. From the top you can see the whole Meridian.' },
    { id: 'skyport', name: 'The Skyport', entity: 'skyport', beacon: 'airship', always: true,
      teaser: 'An airship’s spotlight sweeps the clouds.',
      lore: 'Airships dock at the top of the mast, trailing adverts for things nobody needs.' },
    { id: 'the-reactor', name: 'The Reactor', entity: 'reactor', beacon: 'pulse', always: true,
      teaser: 'A blue heartbeat pulses in the north.',
      lore: 'A fusion core humming at the centre of everything. The whole city runs on its pulse.' },
    { id: 'verdant-dome', name: 'The Verdant Dome', entity: 'dome', beacon: 'wisps',
      teaser: 'A green glow breathes under glass.',
      lore: 'A whole forest under a dome, and the only place in the city where you can hear birds.' },
    { id: 'the-foundry', name: 'The Foundry', entity: 'foundryStacks', beacon: 'smoke', always: true,
      teaser: 'Furnace light flickers in the east.',
      lore: 'Where the city’s machines are born. It never sleeps, and neither do its robots.' },
    { id: 'data-vaults', name: 'The Data Vaults', entity: 'vaultCore', beacon: 'blink',
      teaser: 'Thousands of tiny lights blink in rhythm.',
      lore: 'Every question anyone ever asked the city is stored here. Some are still waiting for answers.' },
    { id: 'great-dam', name: 'The Great Dam', entity: 'dam', beacon: 'mist',
      teaser: 'Water roars somewhere beyond the city.',
      lore: 'It holds back a lake the size of a district and lights half the Meridian.' },
    { id: 'wind-ridge', name: 'Wind Ridge', entity: 'turbine', beacon: 'sails',
      teaser: 'Giant blades turn slowly on the northern ridge.',
      lore: 'The turbines never stop. On windy nights the whole ridge hums.' },
    { id: 'sleeping-titan', name: 'The Sleeping Titan', entity: 'titan', beacon: 'eyes',
      teaser: 'Something huge lies rusting in the western wastes.',
      lore: 'A giant robot from a war nobody remembers winning. Kids climb its fingers.' },
    { id: 'listening-array', name: 'The Listening Array', entity: 'array', beacon: 'rings',
      teaser: 'Radio pings echo from the north-east cliffs.',
      lore: 'Dishes pointed at the stars, listening for someone asking the right question.' },
    { id: 'holo-whale', name: 'The Holo-Whale', entity: 'holowhale', beacon: 'holo', always: true,
      teaser: 'A glowing giant swims through the air above the bay.',
      lore: 'An advert that became a legend. Nobody remembers what it was selling.' },
    { id: 'space-elevator', name: 'The Space Elevator', entity: 'elevator', beacon: 'tether', always: true,
      teaser: 'A line of light climbs straight into the sky.',
      lore: 'A cable all the way to orbit. The ride takes three days, so bring a textbook.' },
    { id: 'launch-isle', name: 'Launch Isle', entity: 'rocket', beacon: 'rocket',
      teaser: 'Something roars on an island to the south-east.',
      lore: 'Rockets leave every Friday. They carry satellites, and occasionally homework.' },
    { id: 'oceanlab', name: 'Oceanlab', entity: 'rig', beacon: 'runes',
      teaser: 'Lights shimmer out on the black water.',
      lore: 'A research rig studying the deep. The fish down there glow brighter than the city.' },
    { id: 'noodle-stand', name: 'Midnight Noodles', find: 'noodle-stand', minor: true, beacon: 'glint',
      teaser: 'Steam and red light spill from an alley.', lore: 'Open all night, every night. The broth recipe is a closely guarded secret.' },
    { id: 'vending-alley', name: 'Vending Alley', find: 'vending-alley', minor: true, beacon: 'glint',
      teaser: 'Something hums and glows in a back street.', lore: 'Forty vending machines in a row. One of them sells maps; nobody knows which.' },
    { id: 'robot-dog', name: 'Byte the Robot Dog', find: 'robot-dog', minor: true, beacon: 'glint',
      teaser: 'Something small is patrolling the market.', lore: 'A delivery bot that decided it would rather be a dog. It fetches.' },
    { id: 'koi-pond', name: 'The Neon Koi Pond', find: 'koi-pond', minor: true, beacon: 'glint',
      teaser: 'Colours move under still water.', lore: 'The koi were engineered to glow. They seem very pleased about it.' },
    { id: 'graffiti-wall', name: 'The Graffiti Wall', find: 'graffiti-wall', minor: true, beacon: 'glint',
      teaser: 'A wall of colour flashes between the blocks.', lore: 'Every artist in the Meridian has left a mark here. Some left equations.' },
    { id: 'hover-wreck', name: 'The Hovercar Wreck', find: 'hover-wreck', minor: true, beacon: 'glint',
      teaser: 'Something crashed in the Canal Quarter.', lore: 'The driver was fine. The pigeon that was sitting there is still annoyed.' },
    { id: 'neon-court', name: 'The Neon Court', find: 'neon-court', minor: true, beacon: 'glint',
      teaser: 'Orange lines glow on the asphalt.', lore: 'Pick-up games at 3am, under lights that never switch off.' },
    { id: 'fortune-bot', name: 'Madame Circuit', find: 'fortune-bot', minor: true, beacon: 'glint',
      teaser: 'A purple booth hums in the Spires.', lore: 'A fortune-telling robot. Its predictions are mostly about exams.' },
    { id: 'cyber-tree', name: 'The Cyber Tree', find: 'cyber-tree', minor: true, beacon: 'glint',
      teaser: 'A glowing tree shines in the park.', lore: 'Half tree, half fibre optics. Nobody planted it; it just grew.' },
    { id: 'drone-nest', name: 'The Drone Nest', find: 'drone-nest', minor: true, beacon: 'glint',
      teaser: 'Tiny lights swarm over the Foundry road.', lore: 'Where delivery drones rest between jobs. They gossip in binary.' },
    { id: 'phone-booth', name: 'The Last Phone Booth', find: 'phone-booth', minor: true, beacon: 'glint',
      teaser: 'A red box glows on a canal corner.', lore: 'The last payphone in the city. It still rings sometimes.' },
    { id: 'cat-cafe', name: 'Neko Byte Café', find: 'cat-cafe', minor: true, beacon: 'glint',
      teaser: 'A pink cat sign flickers in Neon Heights.', lore: 'Seven cats, two robots, excellent tea.' },
    { id: 'old-satellite', name: 'The Fallen Satellite', find: 'old-satellite', minor: true, beacon: 'glint',
      teaser: 'Metal glints in the western sand.', lore: 'It fell out of orbit decades ago. Scavengers still argue about who owns it.' },
    { id: 'glitch-board', name: 'The Glitch Billboard', find: 'glitch-board', minor: true, beacon: 'glint',
      teaser: 'A screen flickers in the Core District.', lore: 'It has shown the same corrupted advert for years. People find it relaxing.' },
    { id: 'skate-bowl', name: 'The Skate Bowl', find: 'skate-bowl', minor: true, beacon: 'glint',
      teaser: 'A violet ring glows in Neon Heights.', lore: 'The best skate spot in the Meridian, and the loudest.' },
    { id: 'food-truck', name: 'Taco Terminal', find: 'food-truck', minor: true, beacon: 'glint',
      teaser: 'A yellow light parks near the Foundry.', lore: 'Feeds the night shift. The hot sauce is rated for industrial use.' },
    { id: 'bot-shrine', name: 'The Bot Shrine', find: 'bot-shrine', minor: true, beacon: 'glint',
      teaser: 'A small light burns below the ridge.', lore: 'Robots leave spare parts here as offerings. Nobody knows who started it.' },
    { id: 'crashed-drone', name: 'The Big Drone', find: 'crashed-drone', minor: true, beacon: 'glint',
      teaser: 'Something large lies among the solar panels.', lore: 'A cargo drone that ran out of battery mid-flight. Very embarrassing for it.' },
  ],
};

const cache = new Map();

/** Landmarks for a world with their anchor tiles resolved. */
export function getLandmarks(world) {
  if (!world) return [];
  if (cache.has(world)) return cache.get(world);
  const level = world.level || 1;
  const list = [];
  for (const spec of SPECS[world.id] || []) {
    let at = null;
    const regionId = spec.island || spec.region;
    if (regionId) {
      const isl = world.islands?.find((i) => i.id === regionId);
      if (isl) at = { x: Math.round(isl.cx), y: Math.round(isl.cy) };
    } else if (spec.entity) {
      const e = world.entities?.find((en) => en.type === spec.entity);
      if (e) at = { x: Math.round(e.x), y: Math.round(e.y) };
    } else if (spec.at === 'falls') {
      at = world.mapData?.river?.falls || world.mapData?.spillway?.falls || null;
    } else if (spec.find) {
      const e = world.entities?.find((en) => en.type === 'find' && en.id === spec.find);
      if (e) at = { x: e.x, y: e.y };
    } else if (Array.isArray(spec.at)) {
      at = { x: spec.at[0], y: spec.at[1] };
    }
    if (!at) continue;
    const x = Math.max(0, Math.min(world.size - 1, at.x));
    const y = Math.max(0, Math.min(world.size - 1, at.y));
    list.push({ ...spec, level, x, y });
  }
  cache.set(world, list);
  return list;
}
