import React from 'react';
import {createRoot} from 'react-dom/client';
import {AuthContext} from '../src/context/authState';
import NotebookPage from '../src/components/NotebookPage/NotebookPage';
import LessonView from '../src/components/NotebookPage/LessonView';
import {lessonChatKey} from '../src/utils/studentCache';

if(location.hostname!=='127.0.0.1')throw Error('Use the isolated local fixture.');
for(const name of ['Memory Palace','Physics'])sessionStorage.removeItem(lessonChatKey(999995,name));
const root=createRoot(document.getElementById('fixture'));
const stages=['Choose what you want to remember','Make your first memorable scene','Build your five-stop route','Walk, recall, and repair','Use it in your own studying'];
const sections=stages.map(title=>({title,estimated_minutes:8,learning_objectives:['This legacy objective must not show.'],workshop:{title,outcome:'A learning target and a familiar place for your palace.',criteria:['Choose five concrete items.','Describe a familiar place.']}}));
const state={has_outline:true,content_ready:true,shared_content_ready:true,sections,total_sections:5,current_section:0,estimated_minutes:45,section_progress:[],section_verified:false,is_complete:false};
const json=data=>new Response(JSON.stringify(data),{headers:{'Content-Type':'application/json'}});
let writes=0;
window.fetch=async(url,options={})=>{
 const path=new URL(url,location.href).pathname;
 if(options.method&&options.method!=='GET')writes++;
 if(path==='/api/notebooks/folders')return json(['Memory Palace']);
 if(path==='/api/lessons/summary')return json({});
 if(path.endsWith('/sources'))return json({sources:[]});
 if(path.endsWith('/uploads'))return json({uploads:[]});
 if(path.endsWith('/oma-ingest'))return json({oma_enabled:true,sources:[],ready_for_roadmap:true});
 if(path.endsWith('/lesson'))return json(state);
 if(path.endsWith('/section-chat/0'))return json({conversation_id:'workshop-fixture',messages:[{role:'pedro',content:'We’ll build a palace for five things you want to remember. What would you like to use from your studies?'}]});
 if(path.endsWith('/lesson-notes'))return json({content_html:'',revision:null});
 throw Error('Unexpected fixture request: '+path);
};
const tick=(ms=50)=>new Promise(r=>setTimeout(r,ms));
const until=async f=>{for(let i=0;i<100;i++){if(f())return;await tick();}throw Error('Timed out');};
const btn=text=>[...document.querySelectorAll('button')].find(n=>n.textContent.trim()===text);
const tab=id=>document.querySelector(`[data-tab="${id}"]`);
const cards=()=>document.querySelectorAll('.lib-card--catalogue');
let checks=0;
const check=(v,t)=>{if(!v)throw Error(t);checks++;document.getElementById('results').textContent+='PASS '+t+'\n';};
const wrap=node=><AuthContext.Provider value={{token:'fixture',user:{id:999995}}}><div className="dark">{node}</div></AuthContext.Provider>;
try{
 root.render(wrap(<NotebookPage/>));await until(()=>tab('lessons'));tab('lessons').click();
 await until(()=>cards().length);
 check(cards().length===5,'Catalogue lists each experience once');
 check(cards()[0].querySelector('.lib-card__title').textContent==='Build your own memory palace','Hands-on pilot comes first with an outcome');
 check(!document.body.textContent.includes('spend on premade'),'Trophies are not advertised as spendable currency');
 btn('Study Skills').click();await tick();
 check(cards().length===1,'Topic filter works');
 cards()[0].click();await until(()=>btn('Start workshop'));
 check(document.querySelector('.fv-workshop-outcome').textContent.includes('five things'),'Workshop overview states a concrete outcome');
 check(document.querySelectorAll('.archipelago-title').length===5,'All five milestones are visible');
 check(!document.querySelector('.fv-v2-sources'),'Curated sources stay hidden');
 check(writes===0,'Browsing the catalogue does not overwrite progress or notes');
 btn('Start workshop').click();await until(()=>document.querySelector('.lv-workshop-goal'));
 check(document.querySelector('.lv-header-section-tag').textContent.includes('Milestone 1'),'Lesson header uses milestone wording');
 check(!document.querySelector('.lv-section-objectives'),'Workshop replaces the old theory objective banner');
 document.querySelector('.lv-workshop-goal summary').click();await tick();
 check(document.querySelector('.lv-workshop-goal').open&&document.querySelectorAll('.lv-workshop-goal li').length===2,'Student can expand the evidence checklist');
 check(document.querySelector('.lv-chat-area').textContent.includes('What would you like'),'Opening restores the existing conversation');
 root.render(null);await tick();
 state.sections=[{title:'Forces',learning_objectives:['Explain net force']}];state.total_sections=1;
 root.render(wrap(<LessonView folderName="Physics"/>));await until(()=>document.querySelector('.lv-section-objectives'));
 check(!document.querySelector('.lv-workshop-goal'),'Ordinary lecture lessons keep their original objectives');
 root.render(null);await tick();state.sections=sections;state.total_sections=5;root.render(wrap(<NotebookPage/>));await until(()=>tab('lessons'));tab('lessons').click();
 await until(()=>cards().length);
 document.getElementById('results').textContent+=`\n${checks} workshop browser checks passed`;
}catch(error){document.getElementById('results').textContent+='FAIL '+error.stack;throw error;}
